### ISSUE TITLE
Deleting user results in 500 - invalid signature

### ISSUE THREAD

**Issue by Xertes0** [mnurzyns/ParkSpaceSharing#37]
Steps to reproduce on a clean database:
 - Login as admin:admin
 - Copy the token from response, and paste it to swagger 'Authorize' thing
 - Try to delete an existing user. In my case `id=2`

Server response:
```
{
  "status": "Internal Server Error",
  "code": 500,
  "message": "invalid signature"
}
```

**Comment by Xertes0** [comment]
I'm also unable to POST `/place` with the same response.

**Comment by papaj-na-wrotkach** [comment]
This may be a bug regarding change from simple `Int32` to `Enum`. I'll check it

**Comment by papaj-na-wrotkach** [comment]
this was a bug regarding use after `std::move()`
