### ISSUE TITLE
Signing up results in 404 - user not found, but the user is created

### ISSUE THREAD

**Issue by Xertes0** [mnurzyns/ParkSpaceSharing#38]
Steps to reproduce on a clean database:
 - Sign up with any credentials. In my case:
```json
{
  "username": "string",
  "email": "string",
  "password": "string"
}
```

Server response:
```json
{
  "status": "Not Found",
  "code": 404,
  "message": "User not found"
}
```

Querying the database for users, shows the user was actually created.

**Comment by papaj-na-wrotkach** [comment]
fixed in 181665026153e9c9889db4512e3ef755f4a978c9
