### ISSUE TITLE
POST /offer always returns 500 - internal server error

### ISSUE THREAD

**Issue by Xertes0** [mnurzyns/ParkSpaceSharing#41]
POST /offer always returns 500 - internal server error.

Server response after querying when:
 - authorized as a regular user
 - supplying valid place_id owned by the authorized user
```json
{
  "status": "Internal Server Error",
  "code": 500,
  "message": "[oatpp::sqlite::Executor::QueryParams::QueryParams()]: Error. Query 'createOffer', parameter 'offer.placeId' - property not found or its type is unknown."
}
```

**Comment by papaj-na-wrotkach** [comment]
check out [dev/#41
](https://github.com/mnurzyns/ParkSpaceSharing/tree/dev/%2341)

**Comment by Xertes0** [comment]
> check out [dev/#41 ](https://github.com/mnurzyns/ParkSpaceSharing/tree/dev/%2341)

Looks good. Can we merge it?
