### ISSUE TITLE
It is possible to supply invalid date to POST /offer

### ISSUE THREAD

**Issue by Xertes0** [mnurzyns/ParkSpaceSharing#45]
## Current behavior
POST /offer responds with 200 and inserts the offer, when supplied with `date_from > date_to` or negative date values as `OfferDto` fields. 

## Expected behavior
POST /offer should respond with 400 - bad request, when supplied with invalid date values.

**Comment by Xertes0** [comment]
This should also be checked in PATCH and PUT.

**Comment by papaj-na-wrotkach** [comment]
Low priority but may be implemented
