### ISSUE TITLE
GET /user, GET /user/{id} should NOT return passwords

### ISSUE THREAD

**Issue by Xertes0** [mnurzyns/ParkSpaceSharing#47]
Title, no explanation needed.

**Comment by papaj-na-wrotkach** [comment]
Ah yes, finally someone pointed it out. As I wrote on our Discord it would be good to have some sort of polymorphism in DTOs so you could create a derived DTO class which hides one field of a base class like password.
I asked about it on oatpp repo and I am waiting for a response.
For now we could just make password a `nullptr` or an empty string when returning DTO in those methods
