### ISSUE TITLE
POST and PUT requests should return 201 - Created, when new entry was created

### ISSUE THREAD

**Issue by Xertes0** [mnurzyns/ParkSpaceSharing#48]
## Current behavior
When making a POST or PUT request to any offer or place endpoint, which results in creating a new offer or a new place, server responds with 200.

## Expected behavior
In this situation, server should respond with 201.

**Comment by papaj-na-wrotkach** [comment]
I disagree, the request responds with a body of a put entity so it's possible to return a HTTP 200 status

**Comment by Xertes0** [comment]
> I disagree, the request responds with a body of a put entity so it's possible to return a HTTP 200 status

Yes, but in the case when HTTP request results in a new offer or parking space created, we should return 201 not 200. At least that is what internet says.

Edit:
[Mozilla web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT#responses)

**Comment by Xertes0** [comment]
Reading up on that, I think all of our POST endpoints should return 201, not 200 when an entry was created.

Edit:
Again [Mozilla web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201)

**Comment by papaj-na-wrotkach** [comment]
In that case should the actual entity be returned as well?

**Comment by Xertes0** [comment]
> In that case should the actual entity be returned as well?

According to [Mozilla's web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201), they should.
