### ISSUE TITLE
Offers should be deleted along with places they are linked to

### ISSUE THREAD

**Issue by Xertes0** [mnurzyns/ParkSpaceSharing#49]
## Current behavior
When deleting a place by `DELETE /place` endpoint, offers that were linked to that offer are not deleted.

## Expected behavior
Offers should be deleted along with places they are linked to.

**Comment by papaj-na-wrotkach** [comment]
Another low priority improvement, but I agree

**Comment by papaj-na-wrotkach** [comment]
I think everything we need is one trigger
