### ISSUE TITLE
Add owner_id filter to search places endpoint

### ISSUE THREAD

**Issue by kamikos** [mnurzyns/ParkSpaceSharing#57]
Currently, there is no filter for searching places by owner_id in the search places endpoint. 
To make it easier for users to retrieve all places with a particular owner's id without having to manually enter the id, I propose adding an owner_id filter to the endpoint.

@papaj-na-wrotkach suggested this solution and I agree that it would be a useful addition. Therefore, I am creating this issue to track the implementation of this feature.

Proposed Changes:

-     Add a filter for owner_id to the search places endpoint.
-     Update the documentation to reflect the new filter.

**Comment by papaj-na-wrotkach** [comment]
It would be nice to add more filters in the future. Examples:
- filtering offers by time range
- filtering places/offers by specifying latitude, longitude and radius (max distance) from it

**Comment by papaj-na-wrotkach** [comment]
@kamikos I am thinking about changing search endpoints from GET to POST and creating search DTOs, what's your opinion?

**Comment by kamikos** [comment]
> @kamikos I am thinking about changing search endpoints from GET to POST and creating search DTOs, what's your opinion?

👍

**Comment by papaj-na-wrotkach** [comment]
check if the pr fulfills your request
