### ISSUE TITLE
Server crashes when no phone number is given in /signup

### ISSUE THREAD

**Issue by Xertes0** [mnurzyns/ParkSpaceSharing#65]
Title.

**Comment by papaj-na-wrotkach** [comment]
I believe it's fixed in latest changes

**Comment by Xertes0** [comment]
> I believe it's fixed in latest changes

Still crashes, I'm using commits from `main` branch.

**Comment by papaj-na-wrotkach** [comment]
will investigate

**Comment by papaj-na-wrotkach** [comment]
fixed in 3fccc35998772f35978c9f6ecc69cec5957fe451 which will be pushed when GH will be operational
