### ISSUE TITLE
PATCH endpoints should return 201 - Created, when new entity was created

### ISSUE THREAD

**Issue by Xertes0** [mnurzyns/ParkSpaceSharing#67]
Follow up from:
 - #66

**Comment by papaj-na-wrotkach** [comment]
I disagree, PATCH does not result in creation of new entity

**Comment by papaj-na-wrotkach** [comment]
> The HTTP 201 Created success status response code indicates that the request has succeeded and has **led to the creation of a resource**.

**Comment by Xertes0** [comment]
> I disagree, PATCH does not result in creation of new entity

It was removed in 7e69697. Sorry, I forgot.

**Comment by papaj-na-wrotkach** [comment]
Ah, okay, I didn't know you were referring to the old behavior of PATCH endpoints
